// Copyright 2026 The HyperComputer Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package hypercomputer

import (
	"math"
	"math/rand/v2"
	"runtime"
	"sort"
	"sync"
	"sync/atomic"
)

const (
	// DefaultMCTSWindow is the context width of the MCTS language model.
	// It is wider than the 4-byte phrase window and the 7-byte ΔK cache.
	DefaultMCTSWindow = 32
	// maxMCTSWindow is the widest context winKey can hold.
	maxMCTSWindow = 32
	// DefaultMCTSBudget is how many tree-search playouts training may spend.
	DefaultMCTSBudget = 128
	// DefaultMCTSMaxBits is the longest program the tree search will write.
	// The exhaustive halt oracle stops at DefaultUMaxBits (12).
	DefaultMCTSMaxBits = 64
	// MCTSDecodeHorizon is how many bytes a generation playout scores.
	MCTSDecodeHorizon = 8
	// MCTSDecodeWidth is how many next bytes each node may try.
	MCTSDecodeWidth = 8
	// MCTSDecodeSims is the playout budget for each generated byte.
	MCTSDecodeSims = 32
	// mctsPUCT scales the prior inside the tree policy.
	mctsPUCT = 1.25
	// mctsRepeatLen is the shortest copied phrase the decoder treats as a loop.
	// A cycle whose fundamental period is shorter than this, such as
	// "    .\n", is left alone.
	mctsRepeatLen = 8
	// mctsRepeatPenalty multiplies a playout that extends such a loop.
	mctsRepeatPenalty = 1e-3
)

const errMCTSWindow lmError = "MCTS window is at most 32 bytes"

// mctsAction is one U instruction in the search tree.
type mctsAction struct {
	op, arg int
}

func mctsActions() []mctsAction {
	a := make([]mctsAction, 0, 38)
	for op := 0; op <= uOpJz; op++ {
		a = append(a, mctsAction{op: op})
	}
	for arg := 0; arg < 16; arg++ {
		a = append(a, mctsAction{op: uOpJmp, arg: arg})
		a = append(a, mctsAction{op: uOpSet, arg: arg})
	}
	return a
}

func (a mctsAction) bits() []bool {
	p := make([]bool, 0, 7)
	putBits(&p, a.op, 3)
	if a.op == uOpJmp || a.op == uOpSet {
		putBits(&p, a.arg, 4)
	}
	return p
}

type mctsNode struct {
	bits   []bool
	kids   []*mctsNode
	order  []int
	next   int
	visits int
	value  float64
	dead   bool
}

type mctsHit struct {
	prog []bool
	k    int
	how  string
}

// MCTSOracle is a halt oracle for U grown by Monte Carlo tree search.
// Each playout writes a prefix-free program and runs U. Programs longer
// than the exhaustive 12-bit oracle are ordinary nodes in the tree, so a
// context of dozens of bytes can still be given a halting witness.
type MCTSOracle struct {
	MaxBits int
	Bound   int
	C       float64
	Left    int
	Per     int
	root    *mctsNode
	halt    map[string]bool
	best    map[string]mctsHit
	actions []mctsAction
	mu      sync.Mutex
	seed    uint64
	slots   chan struct{}
	settled atomic.Bool
	Evals   int
	HaltN   int
}

// mctsProcs is how many playouts and scoring chunks run at once.
func mctsProcs() int {
	n := runtime.GOMAXPROCS(0)
	if n < 1 {
		return 1
	}
	return n
}

// NewMCTSOracle searches programs of at most maxBits and runs each one
// for at most bound steps. seed fixes each worker's playout stream.
func NewMCTSOracle(maxBits, bound int, seed uint64) *MCTSOracle {
	if maxBits < DefaultUMaxBits+1 {
		maxBits = DefaultMCTSMaxBits
	}
	if bound < 1 {
		bound = DefaultUBound
	}
	if seed == 0 {
		seed = 1
	}
	return &MCTSOracle{
		MaxBits: maxBits,
		Bound:   bound,
		C:       math.Sqrt2,
		Per:     8,
		root:    &mctsNode{},
		halt:    make(map[string]bool),
		best:    make(map[string]mctsHit),
		actions: mctsActions(),
		seed:    seed,
		slots:   make(chan struct{}, mctsProcs()),
	}
}

// Visits is the number of playouts that have backed up through the root.
func (o *MCTSOracle) Visits() int {
	if o == nil || o.root == nil {
		return 0
	}
	o.mu.Lock()
	defer o.mu.Unlock()
	return o.root.visits
}

// Halts reports whether prog was evaluated, and whether that run was a
// complete halting program.
func (o *MCTSOracle) Halts(prog []bool) (halt, known bool) {
	if o == nil || len(prog) == 0 {
		return false, false
	}
	key := FormatBits(prog)
	if o.settled.Load() {
		h, ok := o.halt[key]
		return h, ok
	}
	o.mu.Lock()
	h, ok := o.halt[key]
	o.mu.Unlock()
	return h, ok
}

// OracleBits packs the evaluated halt bits in lexicographic order of
// the program bit strings. Bit i is 1 when that program halts.
func (o *MCTSOracle) OracleBits() []bool {
	if o == nil {
		return nil
	}
	o.mu.Lock()
	if len(o.halt) == 0 {
		o.mu.Unlock()
		return nil
	}
	halt := make(map[string]bool, len(o.halt))
	for k, v := range o.halt {
		halt[k] = v
	}
	o.mu.Unlock()
	keys := make([]string, 0, len(halt))
	for k := range halt {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	bits := make([]bool, len(keys))
	for i, k := range keys {
		bits[i] = halt[k]
	}
	return bits
}

// Search runs sims playouts aimed at printing target. A nil target
// rewards every halting program, which fills the oracle. The result is
// the shortest witness found for target, including listing and byte-run.
// Playouts run together, one goroutine per worker.
func (o *MCTSOracle) Search(target []bool, sims int) (prog []bool, k int, how string) {
	prog, k, how = o.considerTarget(target)
	if sims < 1 {
		return prog, k, how
	}
	o.play(target, sims)
	return o.witnessOf(target, prog, k, how)
}

// Witness returns a certified program for target, spending a slice of
// the remaining search budget when the tree might shorten the template.
func (o *MCTSOracle) Witness(target []bool) (prog []bool, k int, how string) {
	if len(target) == 0 {
		return nil, -1, ""
	}
	if o.settled.Load() {
		if hit, ok := o.best[FormatBits(target)]; ok {
			return hit.prog, hit.k, hit.how
		}
	}
	prog, k, how = o.considerTarget(target)
	o.mu.Lock()
	n := o.Per
	if n > o.Left {
		n = o.Left
	}
	if n < 1 {
		o.mu.Unlock()
		return prog, k, how
	}
	o.Left -= n
	o.mu.Unlock()
	o.play(target, n)
	return o.witnessOf(target, prog, k, how)
}

func (o *MCTSOracle) witnessOf(target, prog []bool, k int, how string) ([]bool, int, string) {
	if len(target) == 0 {
		return prog, k, how
	}
	key := FormatBits(target)
	o.mu.Lock()
	hit, ok := o.best[key]
	o.mu.Unlock()
	if !ok {
		return prog, k, how
	}
	return hit.prog, hit.k, hit.how
}

func (o *MCTSOracle) considerTarget(target []bool) (prog []bool, k int, how string) {
	if len(target) == 0 {
		return nil, -1, ""
	}
	key := FormatBits(target)
	o.mu.Lock()
	if hit, ok := o.best[key]; ok {
		o.mu.Unlock()
		return hit.prog, hit.k, hit.how
	}
	o.mu.Unlock()
	r := &KResult{K: -1, Bound: o.Bound}
	considerTemplates(target, o.Bound, r)
	if r.Program == nil || r.K < 0 {
		return nil, -1, ""
	}
	o.mu.Lock()
	defer o.mu.Unlock()
	if hit, ok := o.best[key]; ok {
		return hit.prog, hit.k, hit.how
	}
	o.certify(r.Program)
	o.best[key] = mctsHit{prog: append([]bool(nil), r.Program...), k: r.K, how: r.How}
	return o.best[key].prog, r.K, r.How
}

// play runs sims playouts on separate goroutines. Each worker keeps its
// own random stream. The tree records a visit before the rollout returns,
// so two workers do not walk the same untried action.
func (o *MCTSOracle) play(target []bool, sims int) {
	if sims < 1 {
		return
	}
	workers := mctsProcs()
	if workers > sims {
		workers = sims
	}
	var wg sync.WaitGroup
	for id := 0; id < workers; id++ {
		n := sims / workers
		if id < sims%workers {
			n++
		}
		wg.Add(1)
		go func(id, n int) {
			defer wg.Done()
			rng := rand.New(rand.NewPCG(o.seed, uint64(id+1)))
			for i := 0; i < n; i++ {
				o.playout(target, rng)
			}
		}(id, n)
	}
	wg.Wait()
}

func (o *MCTSOracle) playout(target []bool, rng *rand.Rand) {
	o.mu.Lock()
	path := []*mctsNode{o.root}
	o.root.visits++
	n := o.root
	for {
		if n.dead || len(n.bits) >= o.MaxBits {
			break
		}
		if n.order == nil {
			n.order = o.feasible(n.bits, rng)
		}
		if n.next < len(n.order) {
			child := o.expand(n)
			child.visits++
			path = append(path, child)
			n = child
			break
		}
		if len(n.kids) == 0 {
			break
		}
		n = o.bestChild(n)
		n.visits++
		path = append(path, n)
	}
	start := append([]bool(nil), n.bits...)
	complete := n.dead
	o.mu.Unlock()

	prog, res, reward, hit := o.rollout(rng, start, complete, target)

	o.mu.Lock()
	o.note(prog, res)
	if hit {
		o.save(target, prog, "mcts")
	}
	for _, node := range path {
		node.value += reward
	}
	o.mu.Unlock()
}

func (o *MCTSOracle) feasible(prefix []bool, rng *rand.Rand) []int {
	order := make([]int, 0, len(o.actions))
	for i, a := range o.actions {
		if len(prefix)+len(a.bits()) <= o.MaxBits {
			order = append(order, i)
		}
	}
	rng.Shuffle(len(order), func(i, j int) {
		order[i], order[j] = order[j], order[i]
	})
	return order
}

func (o *MCTSOracle) expand(n *mctsNode) *mctsNode {
	a := o.actions[n.order[n.next]]
	n.next++
	bits := make([]bool, 0, len(n.bits)+7)
	bits = append(bits, n.bits...)
	bits = append(bits, a.bits()...)
	child := &mctsNode{bits: bits, dead: a.op == uOpHalt}
	n.kids = append(n.kids, child)
	return child
}

func (o *MCTSOracle) bestChild(n *mctsNode) *mctsNode {
	logN := math.Log(float64(max(n.visits, 1)))
	best := n.kids[0]
	bestS := math.Inf(-1)
	for _, c := range n.kids {
		s := math.Inf(1)
		if c.visits > 0 {
			s = c.value/float64(c.visits) + o.C*math.Sqrt(logN/float64(c.visits))
		}
		if s > bestS {
			bestS = s
			best = c
		}
	}
	return best
}

func (o *MCTSOracle) rollout(rng *rand.Rand, start []bool, complete bool, target []bool) (prog []bool, res UResult, reward float64, hit bool) {
	prog = append([]bool(nil), start...)
	if !complete {
		for len(prog) < o.MaxBits {
			if len(prog) > DefaultUMaxBits && rng.IntN(4) == 0 {
				if hb := (mctsAction{op: uOpHalt}).bits(); len(prog)+len(hb) <= o.MaxBits {
					prog = append(prog, hb...)
				}
				break
			}
			a := o.actions[rng.IntN(len(o.actions))]
			if a.op == uOpHalt && len(prog) <= DefaultUMaxBits {
				a = mctsAction{op: uOpOut0}
			}
			b := a.bits()
			if len(prog)+len(b) > o.MaxBits {
				if hb := (mctsAction{op: uOpHalt}).bits(); len(prog)+len(hb) <= o.MaxBits {
					prog = append(prog, hb...)
				}
				break
			}
			prog = append(prog, b...)
			if a.op == uOpHalt {
				break
			}
		}
	}
	res = o.run(prog)
	if res.Status == UHalt && res.Read == len(prog) && len(target) > 0 && bitsEq(res.Out, target) {
		hit = true
		reward = 1 + float64(o.MaxBits-len(prog))/float64(o.MaxBits)
		return
	}
	if len(target) == 0 {
		if res.Status == UHalt && res.Read == len(prog) {
			reward = 1
		}
		return
	}
	reward = float64(prefixMatch(res.Out, target)) / float64(len(target)+1)
	return
}

func (o *MCTSOracle) run(prog []bool) UResult {
	if o.slots != nil {
		o.slots <- struct{}{}
		defer func() { <-o.slots }()
	}
	return RunU(prog, o.Bound)
}

// certify records prog as a complete halting program. The caller holds o.mu.
func (o *MCTSOracle) certify(prog []bool) {
	if len(prog) == 0 {
		return
	}
	key := FormatBits(prog)
	if h, seen := o.halt[key]; seen {
		if !h {
			o.halt[key] = true
			o.HaltN++
		}
		return
	}
	o.halt[key] = true
	o.Evals++
	o.HaltN++
}

// note records one run of prog. The caller holds o.mu.
func (o *MCTSOracle) note(prog []bool, res UResult) {
	if len(prog) == 0 {
		return
	}
	ok := res.Status == UHalt && res.Read == len(prog)
	key := FormatBits(prog)
	if _, seen := o.halt[key]; seen {
		return
	}
	o.halt[key] = ok
	o.Evals++
	if ok {
		o.HaltN++
	}
}

// save keeps the shortest program that printed target. The caller holds o.mu.
func (o *MCTSOracle) save(target, prog []bool, how string) {
	if len(target) == 0 || len(prog) == 0 {
		return
	}
	key := FormatBits(target)
	if hit, ok := o.best[key]; ok && len(prog) >= hit.k {
		return
	}
	o.best[key] = mctsHit{prog: append([]bool(nil), prog...), k: len(prog), how: how}
}

func prefixMatch(out, target []bool) int {
	n := len(out)
	if len(target) < n {
		n = len(target)
	}
	i := 0
	for i < n && out[i] == target[i] {
		i++
	}
	return i
}

// mctxKey is a context of at most maxMCTSWindow bytes.
type mctxKey struct {
	n uint8
	b [maxMCTSWindow]byte
}

func mctxOf(w []byte) mctxKey {
	var key mctxKey
	key.n = uint8(len(w))
	copy(key.b[:], w)
	return key
}

func addMCTX(tallies map[mctxKey]tally, mixed map[mctxKey]map[byte]uint32, key mctxKey, s byte) {
	t := tallies[key]
	if t.total == 0 {
		tallies[key] = tally{total: 1, sym: s, pure: true}
		return
	}
	t.total++
	if t.pure {
		if t.sym != s {
			mixed[key] = map[byte]uint32{t.sym: t.total - 1, s: 1}
			t.pure = false
		}
	} else {
		mixed[key][s]++
	}
	tallies[key] = t
}

// MCTSLM predicts the next byte from a window wider than the exhaustive
// halt oracle can index. A 32-byte suffix is used only after MCTSOracle
// certifies a program that prints it. That count blends into the
// shorter mixture.
type MCTSLM struct {
	Window   int
	ClassOf  [256]int
	Alphabet []byte
	ctx      map[mctxKey]tally
	mixc     map[mctxKey]map[byte]uint32
	back     *MixPhrase
	oracle   *MCTSOracle
	// CachePPL and CacheAcc score the held-out tail with a causal cache.
	// CacheN is how many tail bytes were scored. Training counts stay frozen.
	CachePPL float64
	CacheAcc float64
	CacheN   int
}

// TrainMCTSLM fits the wide-window model on the same split as the mixture.
// The second report is that mixture.
func TrainMCTSLM(text []byte, cfg LMConfig) (*MCTSLM, LMReport, LMReport, error) {
	cfg.norm()
	if cfg.Window < 1 {
		cfg.Window = DefaultMCTSWindow
	}
	if cfg.Window > maxMCTSWindow {
		return nil, LMReport{}, LMReport{}, errMCTSWindow
	}
	back, brep, _, err := CompareMixPhrase(text, cfg)
	if err != nil {
		return nil, LMReport{}, LMReport{}, err
	}
	train, valid, err := splitCorpus(text, cfg)
	if err != nil {
		return nil, LMReport{}, LMReport{}, err
	}
	bound := cfg.Bound
	if need := 32*cfg.Window + 64; bound < need {
		bound = need
	}
	maxBits := cfg.MaxBits
	if maxBits < DefaultMCTSMaxBits {
		maxBits = DefaultMCTSMaxBits
	}
	oracle := NewMCTSOracle(maxBits, bound, cfg.Seed)
	budget := cfg.Sims
	if budget < 1 {
		budget = DefaultMCTSBudget
	}
	oracle.Left = budget
	m := &MCTSLM{
		Window:   cfg.Window,
		ClassOf:  back.base.ClassOf,
		Alphabet: append([]byte(nil), back.base.Alphabet...),
		back:     back,
		oracle:   oracle,
	}
	m.observe(train)
	m.learn()
	nll, c, s, t := m.pass(train)
	vnll, vc, vs, vt := m.pass(valid)
	m.scoreCache(text, len(train))
	cfg.Epochs = 1
	rep, err := finishReport("mcts", cfg, m.Window, nll, c, s, t, vnll, vc, vs, vt)
	return m, rep, brep, err
}

// OracleVisits is the number of tree-search playouts.
func (m *MCTSLM) OracleVisits() int {
	if m == nil || m.oracle == nil {
		return 0
	}
	return m.oracle.Visits()
}

// OracleEvals is how many distinct programs the oracle has run.
func (m *MCTSLM) OracleEvals() int {
	if m == nil || m.oracle == nil {
		return 0
	}
	m.oracle.mu.Lock()
	defer m.oracle.mu.Unlock()
	return m.oracle.Evals
}

// OracleHalts is how many of those programs halted.
func (m *MCTSLM) OracleHalts() int {
	if m == nil || m.oracle == nil {
		return 0
	}
	m.oracle.mu.Lock()
	defer m.oracle.mu.Unlock()
	return m.oracle.HaltN
}

func (m *MCTSLM) observe(text []byte) {
	w := m.Window
	tallies := make(map[mctxKey]tally)
	mixed := make(map[mctxKey]map[byte]uint32)
	for i := w; i < len(text); i++ {
		addMCTX(tallies, mixed, mctxOf(text[i-w:i]), text[i])
	}
	kept := make(map[mctxKey]tally)
	keptMix := make(map[mctxKey]map[byte]uint32)
	for key, t := range tallies {
		if t.total < ppmMinCount {
			continue
		}
		kept[key] = t
		if mm, ok := mixed[key]; ok {
			keptMix[key] = mm
		}
	}
	m.ctx = kept
	m.mixc = keptMix
}

// learn certifies every repeated window, then spends the playout budget
// on the earliest windows. Certification runs on several goroutines.
// The playouts for one window run together. After this, scoring only reads.
func (m *MCTSLM) learn() {
	if m == nil || m.oracle == nil {
		return
	}
	keys := make([]mctxKey, 0, len(m.ctx))
	for key := range m.ctx {
		keys = append(keys, key)
	}
	sort.Slice(keys, func(i, j int) bool { return mctxLess(keys[i], keys[j]) })
	workers := mctsProcs()
	if workers > len(keys) {
		workers = len(keys)
	}
	var wg sync.WaitGroup
	for w := 0; w < workers; w++ {
		wg.Add(1)
		go func(w int) {
			defer wg.Done()
			for i := w; i < len(keys); i += workers {
				raw := keys[i].b[:keys[i].n]
				m.oracle.considerTarget(windowBits(raw))
			}
		}(w)
	}
	wg.Wait()
	left := m.oracle.Left
	for _, key := range keys {
		if left < 1 {
			break
		}
		n := m.oracle.Per
		if n > left {
			n = left
		}
		left -= n
		raw := key.b[:key.n]
		m.oracle.play(windowBits(raw), n)
	}
	m.oracle.Left = left
	m.oracle.settled.Store(true)
}

func mctxLess(a, b mctxKey) bool {
	if a.n != b.n {
		return a.n < b.n
	}
	for i := 0; i < int(a.n); i++ {
		if a.b[i] != b.b[i] {
			return a.b[i] < b.b[i]
		}
	}
	return false
}

// ContextProgram is the halting program the oracle assigns to the
// Window-byte suffix of w.
func (m *MCTSLM) ContextProgram(w []byte) (prog []bool, k int, how string) {
	if m == nil || m.oracle == nil || len(w) < m.Window {
		return nil, -1, ""
	}
	suf := w[len(w)-m.Window:]
	return m.oracle.Witness(windowBits(suf))
}

// Distribution writes the sampling distribution of the byte after ctx.
func (m *MCTSLM) Distribution(ctx []byte) (alphabet []byte, probs []float64) {
	if m == nil || len(m.Alphabet) == 0 {
		return nil, nil
	}
	alphabet = append([]byte(nil), m.Alphabet...)
	probs = make([]float64, len(alphabet))
	m.probs(ctx, probs)
	return alphabet, probs
}

// Generate searches the continuation with Monte Carlo tree search.
// A playout tries one of the MCTSDecodeWidth likeliest bytes, then
// follows the mode out to MCTSDecodeHorizon. The probabilities are the
// Witten-Bell backoff from the longest counted suffix down to the
// unigram. The reward is the geometric mean of those probabilities,
// and a playout that copies an eight-byte phrase is down-weighted.
// Once that copy is in the text, its next byte is removed. A cycle
// with a shorter period is left alone. The byte kept is the one whose
// best playout scored highest. seed fixes tie breaks. Counts and the
// scored mixture stay frozen.
func (m *MCTSLM) Generate(prompt []byte, n int, seed uint64) []byte {
	if n < 0 {
		n = 0
	}
	out := make([]byte, len(prompt), len(prompt)+n)
	copy(out, prompt)
	if n == 0 || m == nil || len(m.Alphabet) == 0 {
		return out
	}
	rng := rand.New(rand.NewPCG(seed, seed^0x9e3779b97f4a7c15))
	p := make([]float64, len(m.Alphabet))
	for i := 0; i < n; i++ {
		b, ok := m.decodeByte(out, MCTSDecodeSims, rng, p)
		if !ok {
			break
		}
		out = append(out, b)
	}
	return out
}

type decChoice struct {
	b byte
	p float64
}

type decNode struct {
	b      byte
	prior  float64
	visits int
	value  float64
	best   float64
	kids   []*decNode
	next   int
	width  []decChoice
}

func (m *MCTSLM) decodeByte(text []byte, sims int, rng *rand.Rand, p []float64) (byte, bool) {
	if sims < 1 {
		sims = MCTSDecodeSims
	}
	root := &decNode{best: -1}
	ctx := make([]byte, 0, len(text)+MCTSDecodeHorizon)
	for i := 0; i < sims; i++ {
		m.decodeSim(root, text, ctx[:0], p)
	}
	var pick *decNode
	for _, c := range root.kids {
		if pick == nil || betterDec(c, pick, rng) {
			pick = c
		}
	}
	if pick == nil {
		return 0, false
	}
	return pick.b, true
}

func betterDec(a, b *decNode, rng *rand.Rand) bool {
	if a.best > b.best+1e-15 {
		return true
	}
	if b.best > a.best+1e-15 {
		return false
	}
	if a.visits != b.visits {
		return a.visits > b.visits
	}
	if a.prior != b.prior {
		return a.prior > b.prior
	}
	return rng.IntN(2) == 0
}

func (m *MCTSLM) decodeSim(root *decNode, text, ctx []byte, p []float64) {
	path := []*decNode{root}
	added := make([]byte, 0, MCTSDecodeHorizon)
	n := root
	var sum float64
	var cnt int
	for len(added) < MCTSDecodeHorizon {
		ctx = append(append(ctx[:0], text...), added...)
		if n.width == nil {
			m.decodeProbs(ctx, p)
			n.width = rankChoices(m.Alphabet, p)
		}
		if len(n.width) == 0 {
			break
		}
		if n.next < len(n.width) {
			ch := n.width[n.next]
			n.next++
			child := &decNode{b: ch.b, prior: ch.p, best: -1}
			n.kids = append(n.kids, child)
			path = append(path, child)
			added = append(added, ch.b)
			sum += math.Log(floorProb(ch.p))
			cnt++
			break
		}
		n = puctChild(n)
		path = append(path, n)
		added = append(added, n.b)
		sum += math.Log(floorProb(n.prior))
		cnt++
	}
	for len(added) < MCTSDecodeHorizon {
		ctx = append(append(ctx[:0], text...), added...)
		m.decodeProbs(ctx, p)
		b, pb := modeChoice(m.Alphabet, p)
		added = append(added, b)
		sum += math.Log(floorProb(pb))
		cnt++
	}
	reward := 0.0
	if cnt > 0 {
		reward = math.Exp(sum / float64(cnt))
	}
	if loopedPlayout(text, added) {
		reward *= mctsRepeatPenalty
	}
	for _, node := range path {
		node.visits++
		node.value += reward
		if reward > node.best {
			node.best = reward
		}
	}
}

func floorProb(p float64) float64 {
	if p < 1e-15 {
		return 1e-15
	}
	return p
}

// DecodeDistribution is the distribution the tree searches. It is the
// Witten-Bell backoff, with the next byte of a repeated phrase removed.
// The scored mixture is unchanged.
func (m *MCTSLM) DecodeDistribution(ctx []byte) (alphabet []byte, probs []float64) {
	if m == nil || len(m.Alphabet) == 0 {
		return nil, nil
	}
	alphabet = append([]byte(nil), m.Alphabet...)
	probs = make([]float64, len(alphabet))
	m.decodeProbs(ctx, probs)
	return alphabet, probs
}

// decodeProbs is the decoding distribution. The backoff replaces the
// scored mixture, whose unseen escape is flat. The byte that would
// continue a copied phrase of at least mctsRepeatLen bytes, at a
// period at least that long, is removed.
func (m *MCTSLM) decodeProbs(ctx []byte, out []float64) {
	if m.back != nil {
		m.back.sampleProbs(ctx, out)
	} else {
		u := 1 / float64(len(out))
		for i := range out {
			out[i] = u
		}
	}
	p := fundamentalPeriod(ctx)
	if p < mctsRepeatLen || p > len(ctx) || len(m.Alphabet) == 0 {
		return
	}
	ban := ctx[len(ctx)-p]
	for i, b := range m.Alphabet {
		if i < len(out) && b == ban {
			out[i] = 0
		}
	}
	normProbs(out)
}

func rankChoices(alphabet []byte, p []float64) []decChoice {
	ch := make([]decChoice, 0, len(alphabet))
	for i, b := range alphabet {
		if i >= len(p) || p[i] <= 0 {
			continue
		}
		ch = append(ch, decChoice{b: b, p: p[i]})
	}
	sort.Slice(ch, func(i, j int) bool {
		if ch[i].p != ch[j].p {
			return ch[i].p > ch[j].p
		}
		return ch[i].b < ch[j].b
	})
	if len(ch) > MCTSDecodeWidth {
		ch = ch[:MCTSDecodeWidth]
	}
	return ch
}

// loopedPlayout reports that added extends a copied phrase whose
// fundamental period is at least mctsRepeatLen. A shorter cycle is
// not a loop: its fundamental period stays below that length.
func loopedPlayout(text, added []byte) bool {
	if len(added) == 0 {
		return false
	}
	full := make([]byte, len(text)+len(added))
	copy(full, text)
	copy(full[len(text):], added)
	p := fundamentalPeriod(full)
	if p < mctsRepeatLen {
		return false
	}
	return matchAt(full, p) >= mctsRepeatLen
}

// fundamentalPeriod is the shortest period whose suffix match is at
// least mctsRepeatLen. Zero means the text has no such copy.
func fundamentalPeriod(text []byte) int {
	maxP := len(text) - 1
	for p := 1; p <= maxP; p++ {
		if matchAt(text, p) >= mctsRepeatLen {
			return p
		}
	}
	return 0
}

func matchAt(text []byte, p int) int {
	if p < 1 || len(text) <= p {
		return 0
	}
	match := 0
	for i := len(text) - 1; i-p >= 0 && text[i] == text[i-p]; i-- {
		match++
		if match >= mctsRepeatLen {
			return match
		}
	}
	return match
}

func puctChild(n *decNode) *decNode {
	logN := math.Log(float64(max(n.visits, 1)))
	best := n.kids[0]
	bestS := math.Inf(-1)
	for _, c := range n.kids {
		q := 0.0
		if c.visits > 0 {
			q = c.value / float64(c.visits)
		}
		s := q + c.prior*mctsPUCT*math.Sqrt(logN/float64(max(c.visits, 1)))
		if c.visits == 0 {
			s = math.Inf(1)
		}
		if s > bestS {
			bestS = s
			best = c
		}
	}
	return best
}

func modeChoice(alphabet []byte, p []float64) (byte, float64) {
	best, arg := -1.0, 0
	for i, x := range p {
		if i >= len(alphabet) {
			break
		}
		if x > best {
			best, arg = x, i
		}
	}
	if arg >= len(alphabet) {
		return 0, 0
	}
	return alphabet[arg], best
}

// Greedy writes the mode of the wide-window distribution.
func (m *MCTSLM) Greedy(prompt []byte, n int) []byte {
	return m.extend(prompt, n, modeByte)
}

func (m *MCTSLM) extend(prompt []byte, n int, next func(alphabet []byte, p []float64) byte) []byte {
	if n < 0 {
		n = 0
	}
	out := make([]byte, len(prompt), len(prompt)+n)
	copy(out, prompt)
	if n == 0 || m == nil || len(m.Alphabet) == 0 {
		return out
	}
	p := make([]float64, len(m.Alphabet))
	for i := 0; i < n; i++ {
		m.probs(out, p)
		out = append(out, next(m.Alphabet, p))
	}
	return out
}

func (m *MCTSLM) probs(ctx []byte, out []float64) {
	if m.back != nil {
		m.back.probs(ctx, out)
	} else {
		u := 1 / float64(len(out))
		for i := range out {
			out[i] = u
		}
	}
	if len(ctx) < m.Window {
		return
	}
	suf := ctx[len(ctx)-m.Window:]
	t, ok := m.ctx[mctxOf(suf)]
	if !ok || t.total < ppmMinCount {
		return
	}
	prog, k, _ := m.oracle.Witness(windowBits(suf))
	if k < 0 || len(prog) == 0 {
		return
	}
	halt, known := m.oracle.Halts(prog)
	if !known || !halt {
		return
	}
	scratch := make([]float64, len(out))
	copy(scratch, out)
	applyWide(out, scratch, t, m.mixc[mctxOf(suf)], &m.ClassOf)
	normProbs(out)
}

func applyWide(dst, src []float64, t tally, succ map[byte]uint32, classOf *[256]int) {
	kinds := 1
	if !t.pure {
		kinds = len(succ)
	}
	if t.total < 1 || kinds < 1 {
		copy(dst, src)
		return
	}
	esc := float64(kinds) / float64(int(t.total)+kinds)
	scale := 1 / float64(int(t.total)+kinds)
	for i := range dst {
		dst[i] = esc * src[i]
	}
	if t.pure {
		if idx := classOf[t.sym]; idx >= 0 && idx < len(dst) {
			dst[idx] += float64(t.total) * scale
		}
		return
	}
	for b, c := range succ {
		if c == 0 {
			continue
		}
		if idx := classOf[b]; idx >= 0 && idx < len(dst) {
			dst[idx] += float64(c) * scale
		}
	}
}

func (m *MCTSLM) pass(text []byte) (nll float64, correct, scored, total int) {
	if len(text) <= m.Window {
		return 0, 0, 0, 0
	}
	npos := len(text) - m.Window
	workers := mctsProcs()
	if workers > npos {
		workers = npos
	}
	type part struct {
		nll                    float64
		correct, scored, total int
	}
	parts := make([]part, workers)
	var wg sync.WaitGroup
	for w := 0; w < workers; w++ {
		wg.Add(1)
		go func(w int) {
			defer wg.Done()
			lo := m.Window + w*npos/workers
			hi := m.Window + (w+1)*npos/workers
			n := len(m.Alphabet)
			p := make([]float64, n)
			var got part
			for i := lo; i < hi; i++ {
				got.total++
				class := m.ClassOf[text[i]]
				if class < 0 {
					continue
				}
				got.scored++
				m.probs(text[:i], p)
				pb := p[class]
				if pb < 1e-15 {
					pb = 1e-15
				}
				got.nll += -math.Log(pb)
				best, arg := p[0], 0
				for j := 1; j < n; j++ {
					if p[j] > best {
						best = p[j]
						arg = j
					}
				}
				if arg == class {
					got.correct++
				}
			}
			parts[w] = got
		}(w)
	}
	wg.Wait()
	for _, got := range parts {
		nll += got.nll
		correct += got.correct
		scored += got.scored
		total += got.total
	}
	return nll, correct, scored, total
}

// byteCache counts bytes already scored on the held-out tail.
// Orders run from the empty suffix through DefaultVarOrder.
type byteCache struct {
	max int
	ctx map[ctxKey]tally
	mix map[ctxKey]map[byte]uint32
}

func newByteCache() *byteCache {
	return &byteCache{
		max: DefaultVarOrder,
		ctx: make(map[ctxKey]tally),
		mix: make(map[ctxKey]map[byte]uint32),
	}
}

func (c *byteCache) add(ctx []byte, s byte) {
	if c == nil {
		return
	}
	lim := len(ctx)
	if lim > c.max {
		lim = c.max
	}
	for k := 0; k <= lim; k++ {
		var key ctxKey
		if k > 0 {
			key = suffixKey(ctx, k)
		}
		addTally(c.ctx, c.mix, key, s)
	}
}

// longest is the longest suffix seen at least ppmMinCount times.
func (c *byteCache) longest(ctx []byte) (t tally, succ map[byte]uint32, k int, ok bool) {
	if c == nil {
		return tally{}, nil, 0, false
	}
	lim := len(ctx)
	if lim > c.max {
		lim = c.max
	}
	for k = lim; k >= 0; k-- {
		var key ctxKey
		if k > 0 {
			key = suffixKey(ctx, k)
		}
		got, found := c.ctx[key]
		if !found || got.total < ppmMinCount {
			continue
		}
		return got, c.mix[key], k, true
	}
	return tally{}, nil, 0, false
}

// blendCache writes λ P_cache + (1−λ) P_mix. λ is c_cache/(c_cache+c_mix)
// for the longest repeated cache suffix. An empty cache leaves P_mix.
func (m *MCTSLM) blendCache(ctx []byte, cache *byteCache, out []float64) {
	m.probs(ctx, out)
	if cache == nil {
		return
	}
	t, succ, k, ok := cache.longest(ctx)
	if !ok || t.total == 0 {
		return
	}
	cCache := int(t.total)
	cMix := m.trainCount(ctx, k)
	den := cCache + cMix
	if den < 1 {
		return
	}
	lam := float64(cCache) / float64(den)
	if lam <= 0 {
		return
	}
	pc := make([]float64, len(out))
	writeEmp(pc, t, succ, &m.ClassOf)
	for i := range out {
		out[i] = lam*pc[i] + (1-lam)*out[i]
	}
	normProbs(out)
}

func writeEmp(dst []float64, t tally, succ map[byte]uint32, classOf *[256]int) {
	for i := range dst {
		dst[i] = 0
	}
	if t.total == 0 || classOf == nil {
		return
	}
	if t.pure {
		if idx := classOf[t.sym]; idx >= 0 && idx < len(dst) {
			dst[idx] = 1
		}
		return
	}
	var z float64
	for b, c := range succ {
		if c == 0 {
			continue
		}
		idx := classOf[b]
		if idx < 0 || idx >= len(dst) {
			continue
		}
		p := float64(c) / float64(t.total)
		dst[idx] += p
		z += p
	}
	if z > 0 {
		for i := range dst {
			dst[i] /= z
		}
	}
}

// trainCount is how often the k-byte suffix of ctx occurred in training.
// Suffixes longer than 4 bytes are counted only when they occurred at
// least twice; a unique training string contributes nothing.
func (m *MCTSLM) trainCount(ctx []byte, k int) int {
	if m == nil || m.back == nil || m.back.long == nil || k < 0 || k > len(ctx) {
		return 0
	}
	v := m.back.long
	if k >= 5 {
		if k > v.Max || v.ctx == nil {
			return 0
		}
		t, ok := v.ctx[suffixKey(ctx, k)]
		if !ok {
			return 0
		}
		return int(t.total)
	}
	if k == 4 {
		b := m.back.base
		if b == nil || b.ctx == nil {
			return 0
		}
		cc := b.ctx[byteKeyOf(ctx[len(ctx)-4:])]
		if cc == nil {
			return 0
		}
		return cc.total
	}
	if v.low == nil {
		return 0
	}
	var key ctxKey
	if k > 0 {
		key = suffixKey(ctx, k)
	}
	t, ok := v.low[key]
	if !ok {
		return 0
	}
	return int(t.total)
}

// scoreCache scores text[cut:] with the causal cache. The context is the
// bytes before the target, so it crosses the cut. The target is counted
// only after it is scored. Training perplexity is left alone.
func (m *MCTSLM) scoreCache(text []byte, cut int) {
	if m == nil || len(m.Alphabet) == 0 || cut < 0 || cut >= len(text) {
		return
	}
	cache := newByteCache()
	n := len(m.Alphabet)
	p := make([]float64, n)
	var nll float64
	var correct, scored, total int
	for i := cut; i < len(text); i++ {
		total++
		class := m.ClassOf[text[i]]
		ctx := text[:i]
		if class >= 0 {
			scored++
			m.blendCache(ctx, cache, p)
			pb := p[class]
			if pb < 1e-15 {
				pb = 1e-15
			}
			nll += -math.Log(pb)
			best, arg := p[0], 0
			for j := 1; j < n; j++ {
				if p[j] > best {
					best = p[j]
					arg = j
				}
			}
			if arg == class {
				correct++
			}
		}
		cache.add(ctx, text[i])
	}
	if scored == 0 || total == 0 {
		return
	}
	m.CacheN = total
	m.CachePPL = math.Exp(nll / float64(scored))
	m.CacheAcc = float64(correct) / float64(total)
}
